service: swatch-serverless
frameworkVersion: '3'

custom:
  tableName: 'color-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ ColorTable, Arn ]
  environment:
    COLOR_TABLE: ${self:custom.tableName}
    REGION: ${self:provider.region}
  logs:
    restApi: true


functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    ColorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

plugins:
  - serverless-offline
